title: Project title in sentence case
hero_image: images/banner.png
description: A short description of the project
listed: false
pdf: false
steps:
  - title: You will make
  - title: What is an Astro Pi?
  - title: Display an image
    completion:
    - engaged
  - title: Sense a colour
    completion:
    - internal
  - title: What next — more Astro Pi projects
    completion:
    - external


